-- ============================================================================
-- SEED DATA: bus_models
-- ============================================================================

insert into bus_models (slug, manufacturer, model, length_ft, fuel_type, year_introduced, description) values
  ('2015-gillig-low-floor-cng-40', 'Gillig', 'Low Floor CNG 40''', 40, 'CNG', 2015, 'Standard 40-foot low-floor CNG bus by Gillig. A workhorse of the MTS fleet with accessible boarding and compressed natural gas power.'),
  ('2025-new-flyer-xn40', 'New Flyer', 'XN40', 40, 'CNG', 2025, 'Brand-new Xcelsior CHARGE NG 40-foot CNG buses. The newest addition to the MTS fleet, featuring modern amenities and improved fuel efficiency.'),
  ('2012-new-flyer-c40lfr', 'New Flyer', 'C40LFR', 40, 'CNG', 2012, 'New Flyer C40LFR low-floor CNG transit bus. One of the older workhorses in the fleet, these buses have been reliably serving San Diego routes since 2012.'),
  ('2013-gillig-low-floor-cng-40', 'Gillig', 'Low Floor CNG 40''', 40, 'CNG', 2013, 'Gillig low-floor 40-foot CNG bus from the 2013 order. Part of a mid-2010s fleet expansion for fixed-route service.'),
  ('2014-gillig-low-floor-cng-40', 'Gillig', 'Low Floor CNG 40''', 40, 'CNG', 2014, 'A small batch of Gillig low-floor CNG buses from 2014. Shares the same reliable platform as the 800-series with minor updates.'),
  ('2013-new-flyer-xn60', 'New Flyer', 'XN60', 60, 'CNG', 2013, '60-foot articulated CNG bus with a bendable joint for high-capacity routes. Among the first XN60 articulateds in the MTS fleet.'),
  ('2015-new-flyer-xn60', 'New Flyer', 'XN60', 60, 'CNG', 2015, 'Articulated 60-foot New Flyer CNG bus. Used on MTS Rapid and other high-ridership corridors where extra passenger capacity is needed.'),
  ('2017-gillig-low-floor-cng-40', 'Gillig', 'Low Floor CNG 40''', 40, 'CNG', 2017, 'Gillig low-floor CNG 40-footer from a 2017 delivery. Features updated interiors compared to earlier Gillig batches.'),
  ('2019-new-flyer-xe40', 'New Flyer', 'XE40', 40, 'Electric', 2019, 'One of the first battery-electric buses in the MTS fleet. These Xcelsior CHARGE 40-footers were a pilot for zero-emission transit in San Diego.'),
  ('2020-gillig-low-floor-plus-ev-40', 'Gillig', 'Low Floor Plus EV 40''', 40, 'Electric', 2020, 'Gillig''s battery-electric variant of their proven low-floor platform. Part of MTS''s early zero-emission rollout alongside the New Flyer XE40s.'),
  ('2020-gillig-low-floor-cng-40', 'Gillig', 'Low Floor CNG 40''', 40, 'CNG', 2020, 'A large 2020 order of Gillig low-floor CNG buses. These 40-footers helped replace aging vehicles across multiple MTS routes.'),
  ('2021-new-flyer-xn60', 'New Flyer', 'XN60', 60, 'CNG', 2021, 'Articulated 60-foot CNG bus for high-demand corridors. Features the updated Xcelsior interior with improved passenger amenities.'),
  ('2023-new-flyer-xn60', 'New Flyer', 'XN60', 60, 'CNG', 2023, 'Recent-model 60-foot articulated CNG buses. These bendies serve MTS Rapid lines and other routes needing maximum passenger throughput.'),
  ('2024-new-flyer-xn60', 'New Flyer', 'XN60', 60, 'CNG', 2024, 'The newest articulated CNG buses in the fleet. A small 2024 follow-on order continuing the XN60 platform on high-ridership routes.'),
  ('2022-gillig-low-floor-cng-40', 'Gillig', 'Low Floor CNG 40''', 40, 'CNG', 2022, 'A 2022 batch of Gillig low-floor CNG 40-footers. Features the latest Gillig interior refresh with improved LED lighting and seating.'),
  ('2021-gillig-low-floor-cng-40', 'Gillig', 'Low Floor CNG 40''', 40, 'CNG', 2021, 'Gillig low-floor CNG 40-footers from a 2021 delivery. Helped refresh the aging mid-2010s Gillig fleet with updated components.'),
  ('2018-gillig-low-floor-cng-40', 'Gillig', 'Low Floor CNG 40''', 40, 'CNG', 2018, 'A small batch of 2018 Gillig CNG buses. These fill-in units supplemented larger orders to meet route coverage needs.'),
  ('2011-new-flyer-c40lfr', 'New Flyer', 'C40LFR', 40, 'CNG', 2011, 'The oldest New Flyer buses still in service. These C40LFR low-floor CNG buses have been workhorses since 2011.'),
  ('2014-ford-eldorado-f550-aero-elite', 'Ford/ElDorado', 'F-550/Aero Elite', 25, 'Gasoline', 2014, 'Compact 25-foot cutaway shuttle bus on a Ford F-550 chassis. Used for lower-ridership community routes and demand-response service.'),
  ('2016-ford-eldorado-f550-aero-elite', 'Ford/ElDorado', 'F-550/Aero Elite', 25, 'LPG', 2016, 'LPG-powered cutaway shuttle on a Ford F-550 chassis. The propane fuel makes these cleaner-burning than their gasoline 3000-series siblings.'),
  ('2019-ford-starcraft-f550-allstar-xl', 'Ford/Starcraft', 'F550/Allstar XL', 25, 'Gasoline', 2019, 'Starcraft-bodied cutaway on a Ford F-550 chassis. A newer shuttle variant used for paratransit and community connector routes.'),
  ('2017-new-flyer-xn60', 'New Flyer', 'XN60', 60, 'CNG', 2017, '60-foot articulated CNG buses assigned to high-frequency services. Part of a 2017 expansion of articulated capacity.'),
  ('2023-new-flyer-xe60', 'New Flyer', 'XE60', 60, 'Electric', 2023, 'Battery-electric 60-foot articulated bus — the largest zero-emission vehicles in the MTS fleet. A major step toward full fleet electrification.'),
  ('2025-new-flyer-xe40', 'New Flyer', 'XE40', 40, 'Electric', 2025, 'The newest and largest batch of battery-electric 40-foot buses. These Xcelsior CHARGE units represent MTS''s accelerating shift to zero-emission transit.'),
  ('2016-gillig-low-floor-cng-40', 'Gillig', 'Low Floor CNG 40''', 40, 'CNG', 2016, 'A 2016 batch of Gillig CNG buses. One of the larger Gillig orders, these buses are distributed across multiple MTS operating divisions.'),
  ('2019-gillig-low-floor-cng-40', 'Gillig', 'Low Floor CNG 40''', 40, 'CNG', 2019, 'A small 2019 follow-on order of Gillig low-floor CNG buses. Supplemented the existing Gillig fleet with updated components.'),
  ('2020-mci-d4500ct-cng', 'MCI', 'D4500CT CNG', 40, 'CNG', 2020, 'Motor Coach Industries commuter coach running on CNG. A highway-style bus with high-back seating, used on longer express and commuter routes.');

-- ============================================================================
-- SEED DATA: fleet_entries
-- ============================================================================

insert into fleet_entries (agency, range_start, range_end, bus_model_id) values
  ('MTS', 201,  223,  (select id from bus_models where slug = '2015-gillig-low-floor-cng-40')),
  ('MTS', 301,  390,  (select id from bus_models where slug = '2025-new-flyer-xn40')),
  ('MTS', 701,  731,  (select id from bus_models where slug = '2012-new-flyer-c40lfr')),
  ('MTS', 801,  826,  (select id from bus_models where slug = '2013-gillig-low-floor-cng-40')),
  ('MTS', 901,  912,  (select id from bus_models where slug = '2014-gillig-low-floor-cng-40')),
  ('MTS', 1201, 1218, (select id from bus_models where slug = '2013-new-flyer-xn60')),
  ('MTS', 1301, 1313, (select id from bus_models where slug = '2015-new-flyer-xn60')),
  ('MTS', 1401, 1410, (select id from bus_models where slug = '2017-gillig-low-floor-cng-40')),
  ('MTS', 1501, 1506, (select id from bus_models where slug = '2019-new-flyer-xe40')),
  ('MTS', 1601, 1607, (select id from bus_models where slug = '2020-gillig-low-floor-plus-ev-40')),
  ('MTS', 1701, 1738, (select id from bus_models where slug = '2020-gillig-low-floor-cng-40')),
  ('MTS', 1801, 1826, (select id from bus_models where slug = '2021-new-flyer-xn60')),
  ('MTS', 1901, 1924, (select id from bus_models where slug = '2023-new-flyer-xn60')),
  ('MTS', 1925, 1929, (select id from bus_models where slug = '2024-new-flyer-xn60')),
  ('MTS', 2001, 2014, (select id from bus_models where slug = '2015-gillig-low-floor-cng-40')),
  ('MTS', 2101, 2136, (select id from bus_models where slug = '2017-gillig-low-floor-cng-40')),
  ('MTS', 2201, 2238, (select id from bus_models where slug = '2022-gillig-low-floor-cng-40')),
  ('MTS', 2301, 2324, (select id from bus_models where slug = '2013-gillig-low-floor-cng-40')),
  ('MTS', 2401, 2438, (select id from bus_models where slug = '2014-gillig-low-floor-cng-40')),
  ('MTS', 2601, 2632, (select id from bus_models where slug = '2021-gillig-low-floor-cng-40')),
  ('MTS', 2781, 2787, (select id from bus_models where slug = '2018-gillig-low-floor-cng-40')),
  ('MTS', 2791, 2795, (select id from bus_models where slug = '2021-gillig-low-floor-cng-40')),
  ('MTS', 2901, 2927, (select id from bus_models where slug = '2011-new-flyer-c40lfr')),
  ('MTS', 3001, 3006, (select id from bus_models where slug = '2014-ford-eldorado-f550-aero-elite')),
  ('MTS', 3101, 3131, (select id from bus_models where slug = '2016-ford-eldorado-f550-aero-elite')),
  ('MTS', 3506, 3508, (select id from bus_models where slug = '2019-ford-starcraft-f550-allstar-xl')),
  ('MTS', 7401, 7410, (select id from bus_models where slug = '2017-new-flyer-xn60')),
  ('MTS', 7501, 7517, (select id from bus_models where slug = '2017-new-flyer-xn60')),
  ('MTS', 7551, 7562, (select id from bus_models where slug = '2023-new-flyer-xe60')),
  ('MTS', 7601, 7691, (select id from bus_models where slug = '2025-new-flyer-xe40')),
  ('MTS', 8201, 8213, (select id from bus_models where slug = '2015-gillig-low-floor-cng-40')),
  ('MTS', 8301, 8338, (select id from bus_models where slug = '2016-gillig-low-floor-cng-40')),
  ('MTS', 8351, 8356, (select id from bus_models where slug = '2019-gillig-low-floor-cng-40')),
  ('MTS', 8531, 8554, (select id from bus_models where slug = '2020-mci-d4500ct-cng'));

-- ============================================================================
-- SEED DATA: bus_routes
-- ============================================================================

insert into bus_routes (slug, agency, route, name) values
  ('mts-1', 'MTS', '1', 'Fashion Valley - La Mesa'),
  ('mts-2', 'MTS', '2', 'Downtown - North Park'),
  ('mts-3', 'MTS', '3', 'UCSD Med. Ctr. / Hillcrest - Euclid Trolley'),
  ('mts-4', 'MTS', '4', 'Lomita Village - 12th & Imperial Transit Ctr'),
  ('mts-5', 'MTS', '5', 'Euclid Trolley - Downtown San Diego / 10th & Broadway'),
  ('mts-6', 'MTS', '6', 'Fashion Valley - North Park'),
  ('mts-7', 'MTS', '7', 'Downtown - University & College'),
  ('mts-8', 'MTS', '8', 'Old Town - Balboa Avenue Transit Center'),
  ('mts-9', 'MTS', '9', 'Pacific Beach via SeaWorld - Old Town via SeaWorld'),
  ('mts-10', 'MTS', '10', 'University & College - Old Town Transit Center'),
  ('mts-11', 'MTS', '11', 'SDSU - Downtown'),
  ('mts-12', 'MTS', '12', 'Skyline Hills - City College'),
  ('mts-13', 'MTS', '13', 'Kaiser Hosp. / Union Grantville Trolley - 24th St. Trolley'),
  ('mts-14', 'MTS', '14', 'Union Grantville Trolley - Baltimore & Lake Murray'),
  ('mts-18', 'MTS', '18', 'Union Grantville - Camino del Rio - Union Grantville'),
  ('mts-20', 'MTS', '20', 'Rancho Bernardo Transit Station - Downtown San Diego'),
  ('mts-25', 'MTS', '25', 'Kearny Mesa Transit Center - Fashion Valley Transit Center'),
  ('mts-27', 'MTS', '27', 'Pacific Beach - Kearny Mesa Transit Center'),
  ('mts-28', 'MTS', '28', 'Shelter Island - Old Town Transit Center'),
  ('mts-30', 'MTS', '30', 'Old Town - UTC / VA Medical Center'),
  ('mts-31', 'MTS', '31', 'UTC - Mira Mesa'),
  ('mts-35', 'MTS', '35', 'Old Town Transit Center - Ocean Beach'),
  ('mts-41', 'MTS', '41', 'UCSD - Fashion Valley Transit Center'),
  ('mts-43', 'MTS', '43', 'Balboa Avenue Transit Center - Kearny Mesa Transit Center'),
  ('mts-44', 'MTS', '44', 'Kearny Mesa - Old Town'),
  ('mts-60', 'MTS', '60', 'UTC via Kearny Mesa - Euclid Av Trolley Station via Kearny Mesa'),
  ('mts-83', 'MTS', '83', 'Old Town - Downtown'),
  ('mts-84', 'MTS', '84', 'Shelter Island - Sub Base / Cabrillo Monument'),
  ('mts-88', 'MTS', '88', 'Fashion Valley Transit Center - Old Town Transit Center'),
  ('mts-105', 'MTS', '105', 'Old Town Transit Center - UTC'),
  ('mts-110', 'MTS', '110', 'Downtown San Diego - Mira Mesa Express'),
  ('mts-115', 'MTS', '115', 'SDSU Transit Center - El Cajon Transit Center'),
  ('mts-120', 'MTS', '120', 'Kearny Mesa Transit Ctr Limited Stops - Downtown Limited Stops'),
  ('mts-201', 'MTS', '201', 'UCSD Medical Center - UCSD - Nobel - UTC'),
  ('mts-202', 'MTS', '202', 'UCSD Medical Center - UCSD - Nobel - UTC'),
  ('mts-204', 'MTS', '204', 'UTC - Executive - Judicial - UTC'),
  ('mts-215', 'MTS', '215', 'SDSU - Downtown'),
  ('mts-225', 'MTS', '225', 'Downtown San Diego - Otay Mesa Transit Center'),
  ('mts-227', 'MTS', '227', 'Otay Mesa Transit Center - Imperial Beach Pier'),
  ('mts-235', 'MTS', '235', 'Downtown San Diego - Escondido Transit Center'),
  ('mts-237', 'MTS', '237', 'Mira Mesa - UC San Diego'),
  ('mts-280', 'MTS', '280', 'Downtown San Diego - Escondido Transit Center'),
  ('mts-290', 'MTS', '290', 'Downtown San Diego - Rancho Bernardo Transit Station'),
  ('mts-701', 'MTS', '701', 'H Street Trolley - Palomar Street Trolley'),
  ('mts-704', 'MTS', '704', 'E Street Trolley - Palomar Street Trolley'),
  ('mts-705', 'MTS', '705', 'Southwestern College - Bayfront / E Street Trolley'),
  ('mts-707', 'MTS', '707', 'Southwestern College - Otay Ranch Town Center'),
  ('mts-709', 'MTS', '709', 'Otay Ranch Town Center - H St. Trolley'),
  ('mts-712', 'MTS', '712', 'Southwestern College - Palomar St. Trolley Station'),
  ('mts-815', 'MTS', '815', 'El Cajon Transit Ctr. - East Main & Madison'),
  ('mts-816', 'MTS', '816', 'Cuyamaca College - El Cajon Transit Ctr.'),
  ('mts-832', 'MTS', '832', 'Santee Town Center - North Santee'),
  ('mts-833', 'MTS', '833', 'El Cajon Transit Center - Santee Trolley Station'),
  ('mts-834', 'MTS', '834', 'Santee Trolley - West Santee - Santee Trolley'),
  ('mts-838', 'MTS', '838', 'East County Sq - Alpine'),
  ('mts-848', 'MTS', '848', 'Lakeside - El Cajon Transit Center'),
  ('mts-851', 'MTS', '851', 'Spring Street Trolley - Spring Valley'),
  ('mts-852', 'MTS', '852', 'Grossmont Transit Center - University & 54th'),
  ('mts-854', 'MTS', '854', 'Grossmont College - Grossmont Transit Center'),
  ('mts-855', 'MTS', '855', 'Spring Street Trolley - Rancho San Diego'),
  ('mts-856', 'MTS', '856', 'SDSU - Rancho SD / Cuyamaca College'),
  ('mts-864', 'MTS', '864', 'El Cajon Transit Center - East County Square'),
  ('mts-872', 'MTS', '872', 'El Cajon Shuttle Loop'),
  ('mts-874', 'MTS', '874', 'El Cajon Transit Center - East El Cajon'),
  ('mts-875', 'MTS', '875', 'El Cajon Transit Center - East El Cajon'),
  ('mts-888', 'MTS', '888', 'Jacumba / Campo - El Cajon'),
  ('mts-891', 'MTS', '891', 'Borrego Springs via Shelter Valley - El Cajon'),
  ('mts-892', 'MTS', '892', 'Borrego Springs via Ranchita - El Cajon'),
  ('mts-894', 'MTS', '894', 'Tecate - Campo - Morena Village - El Cajon'),
  ('mts-901', 'MTS', '901', 'Downtown San Diego - Iris Trolley'),
  ('mts-904', 'MTS', '904', 'Ferry Landing - Coronado City Hall'),
  ('mts-905', 'MTS', '905', 'Otay Mesa Transit Center - Iris Trolley'),
  ('mts-906', 'MTS', '906', 'San Ysidro/International Border - Iris Trolley'),
  ('mts-907', 'MTS', '907', 'San Ysidro/International Border - Iris Trolley'),
  ('mts-909', 'MTS', '909', 'Otay Mesa Transit Center - Southwestern College at Otay Mesa'),
  ('mts-910', 'MTS', '910', 'Overnight Express: San Ysidro Transit Center - Downtown San Diego'),
  ('mts-916', 'MTS', '916', 'Streamview - College Grove - Massachusetts Av - Euclid'),
  ('mts-917', 'MTS', '917', 'Streamview - College Grove - Massachusetts Av - Euclid'),
  ('mts-921', 'MTS', '921', 'UTC - Mira Mesa'),
  ('mts-923', 'MTS', '923', 'Ocean Beach - Downtown'),
  ('mts-928', 'MTS', '928', 'Fashion Valley Transit Center - Kearny Mesa Transit Center'),
  ('mts-929', 'MTS', '929', 'Iris Transit Center - 12th & Imperial'),
  ('mts-932', 'MTS', '932', '8th St Trolley - Iris Ave Transit Center'),
  ('mts-933', 'MTS', '933', 'Walmart - Palm Av - Seacoast - I.B. Blvd - Iris'),
  ('mts-934', 'MTS', '934', 'Walmart - Palm Av - Seacoast - I.B. Blvd - Iris'),
  ('mts-936', 'MTS', '936', 'SDSU Transit Center - Spring Valley'),
  ('mts-944', 'MTS', '944', 'Poway - Sabre Springs Transit Station'),
  ('mts-945', 'MTS', '945', 'Rancho Bernardo Transit Station - Old Poway Park'),
  ('mts-945a', 'MTS', '945A', 'Poway Loop'),
  ('mts-955', 'MTS', '955', 'SDSU Transit Center - 8th Street Trolley'),
  ('mts-961', 'MTS', '961', '24th Street Trolley - Encanto / 62nd Street Trolley'),
  ('mts-962', 'MTS', '962', 'Spring Valley - 8th Street Trolley'),
  ('mts-963', 'MTS', '963', '8th Street Transit Center - Paradise Hills'),
  ('mts-964', 'MTS', '964', 'Alliant International University - Camino Ruiz & Capricorn'),
  ('mts-965', 'MTS', '965', 'City Heights Circulator'),
  ('mts-967', 'MTS', '967', '24th St Transit Center - Division/Ava'),
  ('mts-968', 'MTS', '968', '8th Street Transit Center - Plaza Bonita'),
  ('mts-985', 'MTS', '985', 'UC San Diego - N. Torrey Pines'),
  ('mts-992', 'MTS', '992', 'Downtown - Airport - Downtown');
