[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  PUBLIC_SUPABASE_URL = "https://bmwctnuvuoiseucszgiz.supabase.co"
  PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_yqJmNVoXxLfdqt6PzO0wAw_pYM4rfxt"

[context.deploy-preview.environment]
  PUBLIC_SUPABASE_URL = "https://hamiqvohjwrnxdhwokve.supabase.co"
  PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_KHP8lhfJUZZkX5XDhw7Uww_f9Fuz-_Q"
