[build]
  command = "npm run build && curl --silent -X POST https://api.honeybadger.io/v1/deploys -F api_key=$PUBLIC_HONEYBADGER_API_KEY -F deploy[environment]=$PUBLIC_HONEYBADGER_ENVIRONMENT -F deploy[revision]=$COMMIT_REF -F deploy[repository]=$REPOSITORY_URL"
  publish = "build"

[build.environment]
  PUBLIC_HONEYBADGER_API_KEY = "hbp_3Qw5xkDPS6kaP6PTKSBynEsW3FTY202yJFGy"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  PUBLIC_SUPABASE_URL = "https://bmwctnuvuoiseucszgiz.supabase.co"
  PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_yqJmNVoXxLfdqt6PzO0wAw_pYM4rfxt"
  PUBLIC_HONEYBADGER_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  PUBLIC_SUPABASE_URL = "https://hamiqvohjwrnxdhwokve.supabase.co"
  PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_KHP8lhfJUZZkX5XDhw7Uww_f9Fuz-_Q"
  PUBLIC_HONEYBADGER_ENVIRONMENT = "preview"
